<footer>
    <div class="row">
        <div class="col-md-12 footer-marcas ">
            <div class="col-md-6 col-sm-6">
                <img
                    src="<?php echo $this->serverUrl(); ?>/assets/application/img/ministerio-educacao.png"
                    alt="Minist&eacute;rio da Educa&ccedil;&atilde;o">
            </div>
            <div class="col-md-6 col-sm-6 upper">
                <div class="assinatura">
                    Plataforma Carolina Bori <span>Sistema Nacional de
                    Revalida&ccedil;&atilde;o e Reconhecimento de Diplomas</span>
                </div>
            </div>
        </div>
        <div class="col-md-12 navegador-alerta text-center">
            <div class="separador">
                <i class="fa fa-caret-down"></i>
            </div>
            <i class="fa fa-flag "></i>
            <p>Requisitos m&iacute;nimos: Navegador: Internet Explorer 8.0 (ou
                superior), Mozilla Firefox 3.5 (ou superior).</p>
        </div>
        <div class="col-md-12 copyright text-center">
            <p><span><?php echo $this->version() ?></span> - Todos os direitos reservados.</p>
        </div>
    </div>
</footer>
