<body>

<!-- Top content -->
<div class="top-content">
    <div class="inner-bg">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2 text">
                    <h1><strong>Ortho Life</strong> Login</h1>

                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 form-box">
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3>Login do Sistema</h3>
                            <p>Entre com seu usuário e senha abaixo:</p>
                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-lock"></i>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <form  role="form" action="" method="post" class="form-horizontal">
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <label class="sr-only" for="form-username">Usuário</label>
                                    <input type="text" name="form-username" placeholder="Usuário..."
                                           class="form-username form-control" id="form-username">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <label class="sr-only" for="form-password">Senha</label>
                                    <input type="password" name="form-password" placeholder="Senha..."
                                           class="form-password form-control" id="form-password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn btn-success"><i class="fa fa-check">&nbsp;</i>Acessar
                                    </button>
                                </div>
                            </div>
                            <div class="form-group ">
                                <div class="col-sm-6">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-user">&nbsp;</i>Solicitar Acesso
                                    </button>
                                </div>
                                <div class="col-sm-6">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-key">&nbsp;</i>Esqueci
                                        a Senha
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div> <!--div do box preto-->
            </div>
        </div>
    </div>
</div>

<!-- Javascript -->
<script type="text/javascript" src="assets/js/jquery.backstretch.min.js"></script>

</body>


